### ISSUE TITLE
Choose an Activity

### ISSUE THREAD

**Issue by FalconFalcon** [FalconFalcon/Paul202#1]
Each of the team member will come up with 3 top Activities that they find interesting. That they liked. The team will then meet to decide which one to pursue.

**Comment by gaganjain** [comment]
I have come up with three technologies which we can implement :
1) Searching Algorithms
2) Finite State Automata
3) Routing and Deadlocks

**Comment by FalconFalcon** [comment]
Finalized the Activity as Finite State Automata.
